spring:
  cloud:
    stream:
      rabbit:
        bindings:
          producer-out-0:
            producer:
              exchangeType: direct
              routing-key-expression: "'rabbit-producer.to.rabbit-processor'"
      bindings:
        producer-out-0:
          destination: sample.queue
          group: processor
          binder: rabbit
      binder:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbit:
                deliveryMode: ${DELIVERY_MODE:2}
                host: ${RABBIT_HOST:localhost}
                port: ${RABBIT_PORT:5672}
                username: ${RABBIT_USERNAME:guest}
                password: ${RABBIT_PASSWORD:guest}
                virtual-host: ${RABBIT_VHOST:/}
